// Generated from product-owned lead magnet catalogs. Update the source catalogs in each
// product app first, then regenerate this file intentionally.
// Static assets: 177; product-owned dynamic flows: 3.

import type { RequiredLeadMagnet } from './readiness.js'

export const REQUIRED_LEAD_MAGNETS: RequiredLeadMagnet[] = [
  {
    id: 'lm_camaudit_cam_reconciliation_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-reconciliation-checklist',
    name: 'CAM Reconciliation Audit Checklist',
    conversionEventName: 'cam_reconciliation_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-reconciliation-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-reconciliation-audit-checklist.pdf',
  },
  {
    id: 'lm_camaudit_cpa_roi_playbook',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cpa-roi-playbook',
    name: 'CPA Service Line ROI Playbook',
    conversionEventName: 'cpa_roi_playbook_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cpa-roi-playbook',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cpa-service-line-roi-playbook.pdf',
  },
  {
    id: 'lm_camaudit_partnership_playbook',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'partnership-playbook',
    name: 'Commercial Lease Audit Partnership Playbook',
    conversionEventName: 'partnership_playbook_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-partnership-playbook',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/commercial-lease-audit-partnership-playbook.pdf',
  },
  {
    id: 'lm_camaudit_white_label_pricing_sheet',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'white-label-pricing-sheet',
    name: 'White-Label Wholesale Pricing Sheet',
    conversionEventName: 'white_label_pricing_sheet_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-white-label-pricing-sheet',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/white-label-wholesale-pricing-sheet.pdf',
  },
  {
    id: 'lm_camaudit_cam_overbilling_benchmark_2026',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-overbilling-benchmark-2026',
    name: 'State of CAM Overbilling 2026',
    conversionEventName: 'cam_overbilling_benchmark_2026_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-overbilling-benchmark-2026',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-overbilling-benchmark-2026.pdf',
  },
  {
    id: 'lm_camaudit_lease_abstract_cam_fields_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'lease-abstract-cam-fields-checklist',
    name: 'CAM Audit Fields Every Lease Abstract Should Capture',
    conversionEventName: 'lease_abstract_cam_fields_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-lease-abstract-cam-fields-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/lease-abstract-cam-fields-checklist.pdf',
  },
  {
    id: 'lm_camaudit_abstract_to_audit_trigger_scorecard',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'abstract-to-audit-trigger-scorecard',
    name: 'Abstract-to-Audit Trigger Scorecard',
    conversionEventName: 'abstract_to_audit_trigger_scorecard_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-abstract-to-audit-trigger-scorecard',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/abstract-to-audit-trigger-scorecard.pdf',
  },
  {
    id: 'lm_camaudit_opex_clause_abstraction_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'opex-clause-abstraction-checklist',
    name: 'Operating Expense Clause Abstraction Checklist',
    conversionEventName: 'opex_clause_abstraction_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-opex-clause-abstraction-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/opex-clause-abstraction-checklist.pdf',
  },
  {
    id: 'lm_camaudit_audit_rights_extraction_worksheet',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'audit-rights-extraction-worksheet',
    name: 'Audit Rights Extraction Worksheet',
    conversionEventName: 'audit_rights_extraction_worksheet_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-audit-rights-extraction-worksheet',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/audit-rights-extraction-worksheet.pdf',
  },
  {
    id: 'lm_camaudit_lease_abstract_qa_scorecard',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'lease-abstract-qa-scorecard',
    name: 'Lease Abstract QA Scorecard for CAM Clauses',
    conversionEventName: 'lease_abstract_qa_scorecard_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-lease-abstract-qa-scorecard',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/lease-abstract-qa-scorecard.pdf',
  },
  {
    id: 'lm_camaudit_bookkeeper_cam_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'bookkeeper-cam-checklist',
    name: "Bookkeeper's CAM True-Up Red-Flag Checklist",
    conversionEventName: 'bookkeeper_cam_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-bookkeeper-cam-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/bookkeeper-cam-true-up-checklist.pdf',
  },
  {
    id: 'lm_camaudit_rent_cam_coding_guide',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'rent-cam-coding-guide',
    name: 'Rent & CAM Coding Guide for QuickBooks/Xero',
    conversionEventName: 'rent_cam_coding_guide_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-rent-cam-coding-guide',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/rent-cam-coding-guide.pdf',
  },
  {
    id: 'lm_camaudit_landlord_invoice_review_worksheet',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'landlord-invoice-review-worksheet',
    name: 'Landlord Invoice Review Worksheet',
    conversionEventName: 'landlord_invoice_review_worksheet_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-landlord-invoice-review-worksheet',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/landlord-invoice-review-worksheet.pdf',
  },
  {
    id: 'lm_camaudit_cam_bill_client_advisory_script',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-bill-client-advisory-script',
    name: 'Unexpected CAM Bill Client Advisory Script Pack',
    conversionEventName: 'cam_bill_client_advisory_script_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-bill-client-advisory-script',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-bill-client-advisory-script.pdf',
  },
  {
    id: 'lm_camaudit_month_end_close_cam_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'month-end-close-cam-checklist',
    name: 'Month-End Close CAM Escalation Checklist',
    conversionEventName: 'month_end_close_cam_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-month-end-close-cam-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/month-end-close-cam-escalation-checklist.pdf',
  },
  {
    id: 'lm_camaudit_lease_abstract_finance_teams',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'lease-abstract-finance-teams',
    name: 'Lease Abstract for Finance Teams',
    conversionEventName: 'lease_abstract_finance_teams_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-lease-abstract-finance-teams',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/lease-abstract-for-finance-teams.pdf',
  },
  {
    id: 'lm_camaudit_annual_true_up_accrual_decision_tree',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'annual-true-up-accrual-decision-tree',
    name: 'Annual True-Up Accrual Decision Tree',
    conversionEventName: 'annual_true_up_accrual_decision_tree_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-annual-true-up-accrual-decision-tree',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/annual-true-up-accrual-decision-tree.pdf',
  },
  {
    id: 'lm_camaudit_cam_audit_deadline_tracker',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-audit-deadline-tracker',
    name: 'CAM Audit Deadline Tracker',
    conversionEventName: 'cam_audit_deadline_tracker_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-audit-deadline-tracker',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-audit-deadline-tracker.pdf',
  },
  {
    id: 'lm_camaudit_franchise_lease_protection_guide',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'franchise-lease-protection-guide',
    name: 'Franchise Lease Protection Guide',
    conversionEventName: 'franchise_lease_protection_guide_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-franchise-lease-protection-guide',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/franchise-lease-protection-guide.pdf',
  },
  {
    id: 'lm_camaudit_franchise_cam_reconciliation_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'franchise-cam-reconciliation-checklist',
    name: 'Franchise CAM Reconciliation Checklist',
    conversionEventName: 'franchise_cam_reconciliation_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-franchise-cam-reconciliation-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/franchise-cam-reconciliation-checklist.pdf',
  },
  {
    id: 'lm_camaudit_franchise_occupancy_cost_worksheet',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'franchise-occupancy-cost-worksheet',
    name: 'Franchise Occupancy Cost Worksheet',
    conversionEventName: 'franchise_occupancy_cost_worksheet_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-franchise-occupancy-cost-worksheet',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/franchise-occupancy-cost-worksheet.pdf',
  },
  {
    id: 'lm_camaudit_multi_unit_lease_cost_tracker',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'multi-unit-lease-cost-tracker',
    name: 'Multi-Unit Franchise Lease Cost Tracker',
    conversionEventName: 'multi_unit_lease_cost_tracker_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-multi-unit-lease-cost-tracker',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/multi-unit-lease-cost-tracker.pdf',
  },
  {
    id: 'lm_camaudit_franchise_renewal_risk_planner',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'franchise-renewal-risk-planner',
    name: 'Franchise Lease Renewal Risk Planner',
    conversionEventName: 'franchise_renewal_risk_planner_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-franchise-renewal-risk-planner',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/franchise-renewal-risk-planner.pdf',
  },
  {
    id: 'lm_camaudit_qualification_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'qualification-checklist',
    name: 'Partner Prospect Qualification Checklist',
    conversionEventName: 'qualification_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-qualification-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/partner-prospect-qualification-checklist.pdf',
  },
  {
    id: 'lm_camaudit_discovery_call_script',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'discovery-call-script',
    name: 'CAM Audit Discovery Call Script',
    conversionEventName: 'discovery_call_script_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-discovery-call-script',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-audit-discovery-call-script.pdf',
  },
  {
    id: 'lm_camaudit_objection_handling_card',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'objection-handling-card',
    name: 'CAM Audit Objection Handling Card',
    conversionEventName: 'objection_handling_card_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-objection-handling-card',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-audit-objection-handling-card.pdf',
  },
  {
    id: 'lm_camaudit_pricing_worksheet',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'pricing-worksheet',
    name: 'Partner Engagement Pricing Worksheet',
    conversionEventName: 'pricing_worksheet_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-pricing-worksheet',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/partner-engagement-pricing-worksheet.pdf',
  },
  {
    id: 'lm_camaudit_engagement_sop_summary',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'engagement-sop-summary',
    name: 'CAM Audit Engagement SOP Summary',
    conversionEventName: 'engagement_sop_summary_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-engagement-sop-summary',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-audit-engagement-sop-summary.pdf',
  },
  {
    id: 'lm_camaudit_document_request_checklist',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'document-request-checklist',
    name: 'Client Document Request Checklist',
    conversionEventName: 'document_request_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-document-request-checklist',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/client-document-request-checklist.pdf',
  },
  {
    id: 'lm_camaudit_state_upl_notes',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'state-upl-notes',
    name: 'State UPL Notes for Non-Attorney Advisors',
    conversionEventName: 'state_upl_notes_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-state-upl-notes',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/state-upl-notes-for-non-attorney-advisors.pdf',
  },
  {
    id: 'lm_camaudit_cpa_cross_sell_trigger_list',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cpa-cross-sell-trigger-list',
    name: 'CPA Cross-Sell Trigger List',
    conversionEventName: 'cpa_cross_sell_trigger_list_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cpa-cross-sell-trigger-list',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cpa-cross-sell-trigger-list.pdf',
  },
  {
    id: 'lm_camaudit_tenant_rep_handoff_rubric',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'tenant-rep-handoff-rubric',
    name: 'Tenant Rep Handoff Scoring Rubric',
    conversionEventName: 'tenant_rep_handoff_rubric_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-tenant-rep-handoff-rubric',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/tenant-rep-handoff-scoring-rubric.pdf',
  },
  {
    id: 'lm_camaudit_reconciliation_season_calendar',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'reconciliation-season-calendar',
    name: 'Reconciliation Season Pipeline Calendar',
    conversionEventName: 'reconciliation_season_calendar_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-reconciliation-season-calendar',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/reconciliation-season-pipeline-calendar.pdf',
  },
  {
    id: 'lm_camaudit_tenant_rep_cam_audit_revenue_playbook',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'tenant-rep-cam-audit-revenue-playbook',
    name: 'Tenant Rep Broker CAM Audit Revenue Playbook',
    conversionEventName: 'tenant_rep_cam_audit_revenue_playbook_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-tenant-rep-cam-audit-revenue-playbook',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/tenant-rep-cam-audit-revenue-playbook.pdf',
  },
  {
    id: 'lm_camaudit_accounting_firm_white_label_starter_kit',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'accounting-firm-white-label-starter-kit',
    name: 'Accounting Firm White-Label CAM Audit Starter Kit',
    conversionEventName: 'accounting_firm_white_label_starter_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-accounting-firm-white-label-starter-kit',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/accounting-firm-white-label-starter-kit.pdf',
  },
  {
    id: 'lm_camaudit_tenant_rep_cam_audit_proposal_template',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'tenant-rep-cam-audit-proposal-template',
    name: 'Tenant Rep CAM Audit Proposal Template',
    conversionEventName: 'tenant_rep_cam_audit_proposal_template_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-tenant-rep-cam-audit-proposal-template',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/tenant-rep-cam-audit-proposal-template.pdf',
  },
  {
    id: 'lm_camaudit_tenant_rep_cam_audit_deliverables_kit',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'tenant-rep-cam-audit-deliverables-kit',
    name: 'Tenant Rep CAM Audit Deliverables Kit',
    conversionEventName: 'tenant_rep_cam_audit_deliverables_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-tenant-rep-cam-audit-deliverables-kit',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/tenant-rep-cam-audit-deliverables-kit.pdf',
  },
  {
    id: 'lm_camaudit_cam_dispute_letter_attorney_pack',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-dispute-letter-attorney-pack',
    name: 'CAM Dispute Letter Attorney Pack',
    conversionEventName: 'cam_dispute_letter_attorney_pack_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-dispute-letter-attorney-pack',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-dispute-letter-attorney-pack.pdf',
  },
  {
    id: 'lm_camaudit_cpa_cam_audit_workpaper_kit',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cpa-cam-audit-workpaper-kit',
    name: 'CPA CAM Audit Workpaper Kit',
    conversionEventName: 'cpa_cam_audit_workpaper_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cpa-cam-audit-workpaper-kit',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cpa-cam-audit-workpaper-kit.pdf',
  },
  {
    id: 'lm_camaudit_cfo_cam_audit_business_case',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cfo-cam-audit-business-case',
    name: 'CFO CAM Audit Business Case',
    conversionEventName: 'cfo_cam_audit_business_case_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cfo-cam-audit-business-case',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cfo-cam-audit-business-case.pdf',
  },
  {
    id: 'lm_camaudit_property_manager_tenant_side_playbook',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'property-manager-tenant-side-playbook',
    name: 'Property Manager Tenant-Side Playbook',
    conversionEventName: 'property_manager_tenant_side_playbook_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-property-manager-tenant-side-playbook',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/property-manager-tenant-side-playbook.pdf',
  },
  {
    id: 'lm_camaudit_asset_manager_portfolio_audit_template',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'asset-manager-portfolio-audit-template',
    name: 'Asset Manager Portfolio Audit Template',
    conversionEventName: 'asset_manager_portfolio_audit_template_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-asset-manager-portfolio-audit-template',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/asset-manager-portfolio-audit-template.pdf',
  },
  {
    id: 'lm_camaudit_lease_administration_startup_kit',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'lease-administration-startup-kit',
    name: 'Lease Administration Startup Kit',
    conversionEventName: 'lease_administration_startup_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-lease-administration-startup-kit',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/lease-administration-startup-kit.pdf',
  },
  {
    id: 'lm_camaudit_cre_consultant_engagement_pack',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cre-consultant-engagement-pack',
    name: 'CRE Consultant Engagement Pack',
    conversionEventName: 'cre_consultant_engagement_pack_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cre-consultant-engagement-pack',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cre-consultant-engagement-pack.pdf',
  },
  {
    id: 'lm_camaudit_franchise_cam_audit_rollout_plan',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'franchise-cam-audit-rollout-plan',
    name: 'Franchise CAM Audit Rollout Plan',
    conversionEventName: 'franchise_cam_audit_rollout_plan_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-franchise-cam-audit-rollout-plan',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/franchise-cam-audit-rollout-plan.pdf',
  },
  {
    id: 'lm_camaudit_family_office_occupancy_review_kit',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'family-office-occupancy-review-kit',
    name: 'Family Office Occupancy Review Kit',
    conversionEventName: 'family_office_occupancy_review_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-family-office-occupancy-review-kit',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/family-office-occupancy-review-kit.pdf',
  },
  {
    id: 'lm_camaudit_multi_site_cam_audit_business_case',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'multi-site-cam-audit-business-case',
    name: 'Multi-Site CAM Audit Business Case',
    conversionEventName: 'multi_site_cam_audit_business_case_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-multi-site-cam-audit-business-case',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/multi-site-cam-audit-business-case.pdf',
  },
  {
    id: 'lm_camaudit_white_label_cam_audit_partner_kit',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'white-label-cam-audit-partner-kit',
    name: 'White-Label CAM Audit Partner Kit',
    conversionEventName: 'white_label_cam_audit_partner_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-white-label-cam-audit-partner-kit',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/white-label-cam-audit-partner-kit.pdf',
  },
  {
    id: 'lm_camaudit_cam_audit_pricing_models_worksheet',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-audit-pricing-models-worksheet',
    name: 'CAM Audit Pricing Models Worksheet',
    conversionEventName: 'cam_audit_pricing_models_worksheet_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-audit-pricing-models-worksheet',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-audit-pricing-models-worksheet.pdf',
  },
  {
    id: 'lm_camaudit_cam_audit_report_template_pack',
    productId: 'prod_camaudit',
    productSlug: 'camaudit',
    slug: 'cam-audit-report-template-pack',
    name: 'CAM Audit Report Template Pack',
    conversionEventName: 'cam_audit_report_template_pack_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'camaudit-cam-audit-report-template-pack',
    assetR2Bucket: 'camaudit',
    assetR2Key: 'guides/cam-audit-report-template-pack.pdf',
  },
  {
    id: 'lm_floriva_web_cycle_syncing_planner',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'cycle-syncing-planner',
    name: 'Cycle Syncing Planner',
    conversionEventName: 'cycle_syncing_planner_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/cycle-syncing-planner.pdf',
  },
  {
    id: 'lm_floriva_web_cycle_tracking_starter_kit_teens',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'cycle-tracking-starter-kit-teens',
    name: 'Cycle Tracking Starter Kit for Teens',
    conversionEventName: 'cycle_tracking_starter_kit_teens_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/cycle-tracking-starter-kit-teens.pdf',
  },
  {
    id: 'lm_floriva_web_cycle_tracking_starter_template',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'cycle-tracking-starter-template',
    name: 'Cycle Tracking Starter Template',
    conversionEventName: 'cycle_tracking_starter_template_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/cycle-tracking-starter-template.pdf',
  },
  {
    id: 'lm_floriva_web_data_deletion_request_guide',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'data-deletion-request-guide',
    name: 'Data Deletion Request Guide for Period Apps',
    conversionEventName: 'data_deletion_request_guide_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/data-deletion-request-guide.pdf',
  },
  {
    id: 'lm_floriva_web_employer_wellness_app_privacy_audit',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'employer-wellness-app-privacy-audit',
    name: 'Employer Wellness App Privacy Audit Checklist',
    conversionEventName: 'employer_wellness_app_privacy_audit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/employer-wellness-app-privacy-audit.pdf',
  },
  {
    id: 'lm_floriva_web_endometriosis_pain_diary',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'endometriosis-pain-diary',
    name: 'Endometriosis Pain Diary',
    conversionEventName: 'endometriosis_pain_diary_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/endometriosis-pain-diary.pdf',
  },
  {
    id: 'lm_floriva_web_fertility_awareness_method_chart',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'fertility-awareness-method-chart',
    name: 'Fertility Awareness Method Charting Sheet',
    conversionEventName: 'fertility_awareness_method_chart_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/fertility-awareness-method-chart.pdf',
  },
  {
    id: 'lm_floriva_web_flo_to_floriva_switcher_guide',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'flo-to-floriva-switcher-guide',
    name: 'Flo to Floriva Switcher Guide',
    conversionEventName: 'flo_to_floriva_switcher_guide_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/flo-to-floriva-switcher-guide.pdf',
  },
  {
    id: 'lm_floriva_web_florida_georgia_scorecard_bundle',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'florida-georgia-scorecard-bundle',
    name: 'Florida + Georgia Period Tracker Risk Scorecard',
    conversionEventName: 'florida_georgia_scorecard_bundle_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/florida-georgia-scorecard-bundle.pdf',
  },
  {
    id: 'lm_floriva_web_hormone_health_monthly_log',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'hormone-health-monthly-log',
    name: 'Hormone Health Monthly Log',
    conversionEventName: 'hormone_health_monthly_log_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/hormone-health-monthly-log.pdf',
  },
  {
    id: 'lm_floriva_web_pcos_symptom_tracker',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'pcos-symptom-tracker',
    name: 'PCOS Symptom Tracker',
    conversionEventName: 'pcos_symptom_tracker_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/pcos-symptom-tracker.pdf',
  },
  {
    id: 'lm_floriva_web_period_app_privacy_audit_checklist',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'period-app-privacy-audit-checklist',
    name: 'Period App Privacy Audit Checklist',
    conversionEventName: 'period_app_privacy_audit_checklist_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/period-app-privacy-audit-checklist.pdf',
  },
  {
    id: 'lm_floriva_web_period_data_digital_will',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'period-data-digital-will',
    name: 'Period Data Digital Will Template',
    conversionEventName: 'period_data_digital_will_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/period-data-digital-will.pdf',
  },
  {
    id: 'lm_floriva_web_period_tracker_privacy_comparison_matrix',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'period-tracker-privacy-comparison-matrix',
    name: 'Period Tracker Privacy Comparison Matrix',
    conversionEventName: 'period_tracker_privacy_comparison_matrix_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/period-tracker-privacy-comparison-matrix.pdf',
  },
  {
    id: 'lm_floriva_web_post_dobbs_digital_safety_kit',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'post-dobbs-digital-safety-kit',
    name: 'Post-Dobbs Digital Safety Kit',
    conversionEventName: 'post_dobbs_digital_safety_kit_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/post-dobbs-digital-safety-kit.pdf',
  },
  {
    id: 'lm_floriva_web_postpartum_period_return_tracker',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'postpartum-period-return-tracker',
    name: 'Postpartum Period Return Tracker',
    conversionEventName: 'postpartum_period_return_tracker_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/postpartum-period-return-tracker.pdf',
  },
  {
    id: 'lm_floriva_web_privacy_guide',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'privacy-guide',
    name: 'Period Tracker Privacy Guide',
    conversionEventName: 'privacy_guide_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/privacy-guide.pdf',
  },
  {
    id: 'lm_floriva_web_state_risk_scorecard',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'state-risk-scorecard',
    name: 'Period Tracker Risk Scorecard by State',
    conversionEventName: 'state_risk_scorecard_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/state-risk-scorecard.pdf',
  },
  {
    id: 'lm_floriva_web_subpoena_response_template',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'subpoena-response-template',
    name: 'If You Get Subpoenaed: Template + Checklist',
    conversionEventName: 'subpoena_response_template_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/subpoena-response-template.pdf',
  },
  {
    id: 'lm_floriva_web_texas_louisiana_scorecard_bundle',
    productId: 'prod_floriva_web',
    productSlug: 'floriva-web',
    slug: 'texas-louisiana-scorecard-bundle',
    name: 'Texas + Louisiana Period Tracker Risk Scorecard',
    conversionEventName: 'texas_louisiana_scorecard_bundle_downloaded',
    fulfillmentOwner: 'sequencer',
    fulfillmentSequenceSlug: 'floriva-web-lead-magnet-nurture',
    assetR2Bucket: 'floriva-lead-magnets',
    assetR2Key: 'lead-magnets/texas-louisiana-scorecard-bundle.pdf',
  },
]
